export const Colors = {
  bg: {
    // "Paper" canvas. Keep this warm to avoid the default cold-app-grey look.
    primary: '#F2F1EE',
    secondary: '#FFFFFF',
    tertiary: '#EBE9E4',
    coralWash: '#F6EDEA',
    mintWash: '#EAF4EE',
    skyWash: '#E9F2FA',
    brownDark: '#4E3E31',
    brownSoft: '#8A735E',
  },
  text: {
    primary: '#161A18',
    secondary: '#4E5651',
    tertiary: '#77807A',
    inverse: '#FFFFFF',
    brownLight: '#EDE3DB',
  },
  stroke: {
    soft: '#E2DFD9',
    subtle: '#ECEAE5',
    medium: '#CCC7BE',
  },
  accent: {
    primary: '#4E7D68',
    soft: '#E6F2EC',
    dark: '#3B5F4F',
    coral: '#C26B5A',
    mint: '#DDEFE6',
    sky: '#DCECF8',
    amber: '#F2E7D5',
    sun: '#F9F2DF',
    lilac: '#EDE6F4',
  },
  status: {
    success: '#2F7A58',
    successSoft: '#E9F6EF',
    warning: '#8A6A3D',
    warningSoft: '#F7F1E6',
    danger: '#B25F5A',
    dangerSoft: '#F9EDEC',
  },
  semantic: {
    success: '#2F7A58',
    effort: '#8A6A3D',
    streak: '#C26B5A',
    warning: '#8A6A3D',
    insight: '#3B6F8B',
    calm: '#4E7D68',
    reflect: '#6D5C8E',
  },
  semanticSoft: {
    success: '#E9F6EF',
    effort: '#F7F1E6',
    streak: '#FBEDE7',
    warning: '#F7F1E6',
    insight: '#E9F2FA',
    calm: '#E6F2EC',
    reflect: '#F0EAF8',
  },
  ui: {
    overlay: 'rgba(18,21,19,0.36)',
    shimmer: '#E7E6E1',
    divider: '#E2DFD9',
    glass: 'rgba(255,255,255,0.86)',
  },
};
